#!/bin/bash

if [ "$1" == "configure" ]; then
    printf "\n* Pre-installing...\n"

    cat > /tmp/postfix.selections<<EOF
postfix  postfix/compat_conversion_warning: true
postfix  postfix/rfc1035_violation: false
postfix  postfix/lmtp_retired_warning: true
postfix  postfix/mynetworks: 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128
postfix  postfix/main_cf_conversion_warning: true
postfix  postfix/main_mailer_type: No configuration
postfix  postfix/newaliases: false
postfix  postfix/chattr: false
postfix  postfix/mailbox_limit: 0
postfix  postfix/mailname: /etc/mailname
EOF

    debconf-set-selections /tmp/postfix.selections
    rm -f /tmp/postfix.selections
fi

exit 0
